import { ArrowRight, CircleCheck as CheckCircle2, Clock3, Phone, ShieldCheck, Star } from "lucide-react";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { images, siteConfig } from "@/data/siteData";

const avatars = ["https://images.pexels.com/photos/14950779/pexels-photo-14950779.jpeg?auto=compress&cs=tinysrgb&h=100&w=100", "https://images.pexels.com/photos/6102841/pexels-photo-6102841.jpeg?auto=compress&cs=tinysrgb&h=100&w=100", "https://images.pexels.com/photos/15019490/pexels-photo-15019490.jpeg?auto=compress&cs=tinysrgb&h=100&w=100"];

export function HeroSection() {
  return <section id="top" className="relative overflow-hidden bg-gradient-to-br from-background via-background to-blue-50/70 py-16 dark:to-blue-950/20 lg:py-24"><div className="absolute inset-0 bg-grid opacity-40" /><div className="container relative grid items-center gap-12 px-4 lg:grid-cols-2"><div className="animate-fade-up"><Badge variant="secondary" className="mb-5 gap-2"><span className="h-2 w-2 rounded-full bg-green-500" />Принимаем заявки сегодня</Badge><h1 className="max-w-2xl text-4xl font-bold tracking-tight sm:text-5xl lg:text-6xl">Ремонт компьютеров и ноутбуков <span className="bg-gradient-to-r from-primary to-cyan-500 bg-clip-text text-transparent">любой сложности</span></h1><p className="mt-5 max-w-xl text-lg leading-relaxed text-muted-foreground">Бесплатная диагностика, гарантия до 2 лет и выезд мастера на дом. Чиним технику быстро и с заботой о вашем времени.</p><div className="mt-7 flex flex-wrap gap-3"><Button size="lg" asChild><a href="#booking">Записаться на ремонт <ArrowRight className="h-4 w-4" /></a></Button><Button size="lg" variant="outline" asChild><a href={siteConfig.phoneHref}><Phone className="h-4 w-4" />{siteConfig.phone}</a></Button></div><div className="mt-7 flex flex-wrap gap-5 text-sm text-muted-foreground"><span className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-primary" />Гарантия до 2 лет</span><span className="flex items-center gap-2"><Clock3 className="h-5 w-5 text-primary" />Выезд за 1 час</span><span className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5 text-primary" />Диагностика бесплатно</span></div><div className="mt-7 flex items-center gap-3"><div className="flex -space-x-2">{avatars.map((src, index) => <Avatar key={src} className="h-9 w-9 border-2 border-background"><AvatarImage src={src} /><AvatarFallback>К{index + 1}</AvatarFallback></Avatar>)}</div><div><div className="flex">{[1, 2, 3, 4, 5].map((item) => <Star key={item} className="h-4 w-4 fill-yellow-400 text-yellow-400" />)}</div><p className="text-xs text-muted-foreground">12 000+ довольных клиентов</p></div></div></div><div className="relative"><div className="rounded-2xl border bg-card p-2 shadow-2xl"><img src={images.hero} alt="Мастер ремонтирует ноутбук" className="aspect-[4/3] w-full rounded-xl object-cover" /></div><div className="absolute -bottom-5 -left-3 rounded-xl border bg-card p-3 shadow-lg sm:-left-6"><p className="text-xs text-muted-foreground">Ремонт завершён</p><p className="font-semibold text-green-600">за 2 часа 15 минут</p></div><div className="absolute -right-3 -top-5 rounded-xl border bg-card p-3 shadow-lg sm:-right-6"><p className="text-xs text-muted-foreground">Гарантия</p><p className="font-semibold text-primary">24 месяца</p></div></div></div></section>;
}
