import { useState } from "react";
import { Check, ChevronRight } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { priceList } from "@/data/siteData";

export function PricingSection() { const [expanded, setExpanded] = useState(false); const rows = expanded ? priceList : priceList.slice(0, 6); return <section id="pricing" className="bg-muted/30 py-20"><div className="container px-4"><div className="mx-auto mb-10 max-w-2xl text-center"><Badge variant="outline">Цены</Badge><h2 className="mt-4 text-3xl font-bold sm:text-4xl">Понятные цены без сюрпризов</h2><p className="mt-3 text-muted-foreground">Финальную стоимость согласуем до начала работ.</p></div><Card className="mx-auto max-w-4xl"><CardContent className="p-0"><div className="hidden grid-cols-[1fr_140px_140px] gap-4 border-b bg-muted/40 px-6 py-4 text-xs font-semibold uppercase text-muted-foreground sm:grid"><span>Услуга</span><span>Стоимость</span><span>Срок</span></div>{rows.map(([service, price, duration], index) => <div key={service}><div className="grid gap-2 px-5 py-4 sm:grid-cols-[1fr_140px_140px] sm:items-center sm:px-6"><div className="flex gap-2"><Check className="mt-0.5 h-4 w-4 text-green-600" /><span className="font-medium">{service}</span></div><strong className="pl-6 text-sm sm:pl-0">{price}</strong><span className="pl-6 text-sm text-muted-foreground sm:pl-0">{duration}</span></div>{index < rows.length - 1 && <Separator />}</div>)}</CardContent></Card><div className="mt-6 text-center"><Button variant="outline" onClick={() => setExpanded(!expanded)}>{expanded ? "Скрыть" : "Показать весь прайс"}<ChevronRight className={`h-4 w-4 transition ${expanded ? "rotate-90" : ""}`} /></Button><p className="mt-3 text-xs text-muted-foreground">Оплата после выполнения работ: карта, наличные или перевод.</p></div></div></section>; }
