import { useState } from "react";
import { ChevronLeft, ChevronRight, Quote, Star } from "lucide-react";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { reviews } from "@/data/siteData";

export function ReviewsSection() { const [active, setActive] = useState(0); const review = reviews[active]; const move = (step: number) => setActive((active + step + reviews.length) % reviews.length); return <section id="reviews" className="bg-muted/30 py-20"><div className="container px-4"><div className="mx-auto mb-10 max-w-2xl text-center"><Badge variant="outline">Отзывы клиентов</Badge><h2 className="mt-4 text-3xl font-bold sm:text-4xl">Нас рекомендуют друзьям</h2><div className="mt-3 flex justify-center gap-2"><span className="flex">{[1, 2, 3, 4, 5].map((item) => <Star key={item} className="h-5 w-5 fill-yellow-400 text-yellow-400" />)}</span><span className="font-semibold">4.9 из 5</span></div></div><Card className="mx-auto max-w-3xl"><CardContent className="p-8 text-center sm:p-12"><Quote className="mx-auto h-10 w-10 text-primary/20" /><p className="mx-auto mt-5 max-w-2xl text-lg leading-relaxed">«{review[2]}»</p><div className="mt-7 flex items-center justify-center gap-3"><Avatar><AvatarImage src={review[3]} /><AvatarFallback>{review[0][0]}</AvatarFallback></Avatar><div className="text-left"><p className="font-semibold">{review[0]}</p><p className="text-sm text-muted-foreground">{review[1]}</p></div></div><div className="mt-8 flex items-center justify-center gap-3"><Button variant="outline" size="icon" onClick={() => move(-1)}><ChevronLeft className="h-4 w-4" /></Button><div className="flex gap-1.5">{reviews.map((item, index) => <button type="button" key={item[0]} aria-label={`Отзыв ${index + 1}`} onClick={() => setActive(index)} className={`h-2 rounded-full transition-all ${index === active ? "w-6 bg-primary" : "w-2 bg-muted-foreground/30"}`} />)}</div><Button variant="outline" size="icon" onClick={() => move(1)}><ChevronRight className="h-4 w-4" /></Button></div></CardContent></Card></div></section>; }
